networks:
  network:

services:
  app:
    image: deniikbal/exocbt:4.6.2-app
    container_name: exocbt_app
    environment:
      - STORAGE_PATH=${STORAGE_PATH}
    ports:
      - ${APP_EXPOSE}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - .env:/app/.env
      - ./storage:/app/storage
    networks:
      - network
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: exocbt_db
    ports:
      - ${DB_EXPOSE}:${DB_PORT}
    networks:
      - network
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
